services:
  db:
    image: postgres:15
    container_name: task-manager-db
    ports:
      - 5420:5432
    environment:
      - POSTGRES_PASSWORD=MySecretPassword
      - POSTGRES_DB=task-manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: